### ISSUE TITLE
Updating venue for a paper

### ISSUE THREAD

**Issue by mboudiaf** [xiaomengyc/Few-Shot-Semantic-Segmentation-Papers#11]
Hi,

Thanks a lot for this awesome repo ! Just dropping a small note to say the paper "Few-Shot Segmentation Without Meta-Learning: A Good Transductive Inference Is All You Need?" has been accepted to CVPR2021, if it's possible to fix the venue !
Thanks again :)

**Comment by xiaomengyc** [comment]
Congratulations！

I have added your paper to the list. Thanks for letting me know!
Cheers!

**Comment by ily666666** [comment]
Malik Boudiaf 你这个论文，看不懂，用词也奇怪
