### ISSUE TITLE
Weakly Supervised FSS

### ISSUE THREAD

**Issue by MSiam** [xiaomengyc/Few-Shot-Semantic-Segmentation-Papers#12]
Hello Just wanted to denote that this paper is published in IJCAI 2020 not on arxiv only.
https://www.ijcai.org/Proceedings/2020/0120.pdf

Thanks for your efforts.

**Comment by xiaomengyc** [comment]
Thanks for letting me know. I have updated the list!

**Comment by MSiam** [comment]
Thanks
