### ISSUE TITLE
Request to add 1 paper to the list 

### ISSUE THREAD

**Issue by SunghwanHong** [xiaomengyc/Few-Shot-Semantic-Segmentation-Papers#17]
Thanks for your great work..!  Would you mind adding the paper [Cost Aggregation Is All You Need for Few-Shot Segmentation](https://arxiv.org/abs/2112.11685)? We just released the paper today. Thanks!

**Comment by xiaomengyc** [comment]
Hi @SunghwanHong ,
Your paper has been added to the list. Thanks for reminding me.

**Comment by SunghwanHong** [comment]
Hi, @xiaomengyc, 
We will be highly appreciated if you could add another line in 2022 section, as we will re-upload the updated version of [Cost Aggregation Is All You Need for Few-Shot Segmentation](https://arxiv.org/abs/2112.11685), which is named "Cost Aggregation with 4D Convolutional Swin Transformer for Few-Shot Segmentation" and is accepted at ECCV'22. The codes and arxiv papers are not here yet but they will be around soon. Meanwhile, you could attach the old links. 

Thanks!
