### ISSUE TITLE
One shot segmentation paper

### ISSUE THREAD

**Issue by AyanKumarBhunia** [xiaomengyc/Few-Shot-Semantic-Segmentation-Papers#2]
https://www.sciencedirect.com/science/article/pii/S0031320319302626?dgcid=rss_sd_all

A deep one-shot network for query-based logo retrieval, Pattern Recognition, 2019. 

I wonder if this paper could be added.

**Comment by xiaomengyc** [comment]
> https://www.sciencedirect.com/science/article/pii/S0031320319302626?dgcid=rss_sd_all
> 
> A deep one-shot network for query-based logo retrieval, Pattern Recognition, 2019.
> 
> I wonder if this paper could be added.

Of course, I have added your paper.
