### ISSUE TITLE
Please add a CVPR 2022 paper

### ISSUE THREAD

**Issue by dahyun-kang** [xiaomengyc/Few-Shot-Semantic-Segmentation-Papers#20]
Hello,

Thank you for managing the awesome repo.
Please consider adding the following paper:

Title: Integrative Few-Shot Learning for Classification and Segmentation
Venue: CVPR 2022
Paper: https://arxiv.org/abs/2203.15712
Code: https://github.com/dahyun-kang/ifsl

Have a great day! 😃

**Comment by xiaomengyc** [comment]
Thanks for the reminding, I have added the paper to the list.
