### ISSUE TITLE
MSANet  paper 

### ISSUE THREAD

**Issue by Ehteshamciitwah** [xiaomengyc/Few-Shot-Semantic-Segmentation-Papers#21]
Kindly add newly **Few-Shot Segmentation SOTA** Paper.
MSANet: Multi-Similarity and Attention Guidance for Boosting Few-Shot Segmentation
https://arxiv.org/abs/2206.09667
https://paperswithcode.com/paper/msanet-multi-similarity-and-attention-1

**Comment by xiaomengyc** [comment]
Hi, sorry I forgot to tell you that I have added your paper to the list.
