### ISSUE TITLE
Please add our APAPNet paper

### ISSUE THREAD

**Issue by gaobb** [xiaomengyc/Few-Shot-Semantic-Segmentation-Papers#22]
Please add our APANet paper which has been accepted by IEEE TMM 2022.

APANet: Adaptive Prototypes Alignment Network for Few-Shot Semantic Segmentation, TMM 2022.

https://ieeexplore.ieee.org/document/9773019

**Comment by xiaomengyc** [comment]
Thanks for the reminder and congratulations on the acceptance!
I have added your paper to the list.
