### ISSUE TITLE
ECCV 2022 few-shot segmentation paper 

### ISSUE THREAD

**Issue by SunghwanHong** [xiaomengyc/Few-Shot-Semantic-Segmentation-Papers#24]
Hi @xiaomengyc,
I just wanted to remind our paper "Cost Aggregation with 4D Convolutional Swin Transformer for Few-Shot Segmentation" with arxiv address: https://arxiv.org/abs/2207.10866   is accepted to ECCV'22. 
Can you please update the list with our paper added? 
Thanks!

**Comment by xiaomengyc** [comment]
Hi, thanks for the reminding.
Is this paper the same to `Cost Aggregation Is All You Need for Few-Shot Segmentation` in the list? 
If it is, I will delete the previous one and add the new paper to the list.

**Comment by SunghwanHong** [comment]
We made significant revisions to the paper, so i think you can leave the old one as it is. Thanks.

**Comment by SunghwanHong** [comment]
Hi, sorry for the reminder.
It seems the list is not yet updated. 
Is something wrong?

**Comment by xiaomengyc** [comment]
Sorry for the late reply. Your paper has been updated! 
Best,
