### ISSUE TITLE
Found a missing paper

### ISSUE THREAD

**Issue by 704051419** [xiaomengyc/Few-Shot-Semantic-Segmentation-Papers#4]
SimPropNet: Improved Similarity Propagation for Few-shot Image Segmentation (IJCAI2020)
[https://arxiv.org/pdf/2004.15014.pdf](url)

**Comment by 704051419** [comment]
and the CRNet and FGN have been accepted by CVPR2020

**Comment by 704051419** [comment]
code of CANET is also available .
[https://github.com/icoz69/CaNet](url)

**Comment by xiaomengyc** [comment]
Thanks! I have updated the list!
