### ISSUE TITLE
Request to add 1 paper to the list

### ISSUE THREAD

**Issue by RyanXLi** [xiaomengyc/Few-Shot-Semantic-Segmentation-Papers#6]
Thanks for your great work! Would you mind adding the paper [FSS-1000: A 1000-Class Dataset for Few-Shot Segmentation](https://openaccess.thecvf.com/content_CVPR_2020/papers/Li_FSS-1000_A_1000-Class_Dataset_for_Few-Shot_Segmentation_CVPR_2020_paper.pdf) to the list? This is a CVPR2020 paper on a few-shot semantic segmentation dataset. Thanks!

**Comment by xiaomengyc** [comment]
Thanks for letting me know! I have added this paper to the list.
