### ISSUE TITLE
Requesting to add a paper

### ISSUE THREAD

**Issue by cheng-01037** [xiaomengyc/Few-Shot-Semantic-Segmentation-Papers#7]
Hi Xiaolin,

Thank you so much for organizing this repository. 

May I kindly ask if you would like to add the following paper `Self-Supervision with Superpixels: Training Few-shot Medical Image Segmentation without Annotation` (ECCV'20) ? Thanks.

Paper link: https://arxiv.org/abs/2007.09886v2

Code link: https://github.com/cheng-01037/Self-supervised-Fewshot-Medical-Image-Segmentation

Best,
Cheng

**Comment by xiaomengyc** [comment]
Hi Cheng,

Thanks for letting me know and congratulations on the acceptance!  Your paper and code have been added to the list.
