### ISSUE TITLE
Some minor details that requires editing

### ISSUE THREAD

**Issue by RyanXLi** [xiaomengyc/Few-Shot-Semantic-Segmentation-Papers#8]
Hi! Thanks again for your great work. While reading through the papers listed here I have noticed some small errors to be corrected.

1. Objectness-Aware One-Shot Semantic Segmentation appears twice
2. CRNet: Cross-Reference Networks for Few-Shot Segmentation is in CVPR2020
3. SSAP: Single-Shot Instance Segmentation With Affinity Pyramid does not work on few-shot learning

**Comment by xiaomengyc** [comment]
Thanks for your kind reminder! I have updated the list. Cheers!
